menu:
  Home: /
  About: /nplus_doc/2016/05/29/about/
  Twitter: https://twitter.com/elleonard_f
  GitHub: https://github.com/elleonard
  FGO: /nplus_doc/2018/02/09/game/fate/fgo/fgo-link/

sidebar: right

widgets:
- search
- category
- recent_posts
- links

links:
  - url: https://www.nicovideo.jp/
    title: niconico
  - url: http://lovingtheflags1986.blog96.fc2.com/
    title: 国旗と酒が待ち遠しいドリル日記

# Duoshuo
duoshuo_shortname: 

fancybox: true

google_analytics:
rss: 
google_site_verification: 
baidu_site_verification: 
icon:

favicon: /favicon/favicon.ico

bottom_link:
  twitter: elleonard_f
  github: elleonard

awesome_kitcode: b51cad8f00

markdown:
  plugins:
    - markdown-it-footnote
